src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Client_Slug__c</fullName>
        <label>Client Slug</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Customer_Pulse__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Pulse</relationshipLabel>
        <relationshipName>Customer_Pulese</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enterprise_Customer_Slug__c</fullName>
        <description>Customer slug recorded in Coursera Prod env</description>
        <inlineHelpText>Customer slug recorded in Coursera Prod env</inlineHelpText>
        <label>Enterprise Customer Slug</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Customer Pulse</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Customer Pulse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pulse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IndustryBuckets__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Industry_Group__c</fullName>
        <label>Industry Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Industry Groups, Categories and Values</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Industry_Group_Clearbit__c</fullName>
        <label>Industry Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_Group__c</fullName>
        <label>Industry Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TriggerHandlerClass.cls
public with sharing class TriggerHandlerClass 
{
    public TriggerHandlerClass(){ 
    }

    public void OnCustomerPulseBeforeInsert(List<Customer_Pulse__c> newList){
        // EXECUTE BEFORE INSERT LOGIC                  
        Set<String> client_slug_set = new Set<String>();
        Map<String,Case> case_map = new Map<String,Case>();
        for(Customer_Pulse__c cp: newList) {
            client_slug_set.add(cp.Enterprise_Customer_Slug__c);
        }
        for(Case c: [Select id, AccountId, Client_Slug__c from Case where Client_Slug__c IN :client_slug_set]) {
            case_map.put(c.Client_Slug__c,c);
        }
        for(Customer_Pulse__c cp: newList) {
            Case c1 = case_map.get(cp.Enterprise_Customer_Slug__c); 
            if(c1 != null) cp.AccountName__c = c1.AccountId;         
        }       
    }

    //Execute this method before insertion of leads
    public void OnLeadBeforeInsert(List<Lead> newLeads) {
        List<Lead> leadsToUpdate = new List<Lead>();   
        for (Lead l: newLeads) {
            if(l.Industry != Null){
                leadsToUpdate.add(l);
            }
        }
        if(leadsToUpdate.size() > 0) UpdateLeadsWithIndustryGroup(leadsToUpdate);

    }

    //Execute this method before updating leads
    public void OnLeadBeforeUpdate(List<Lead> newLeads) {
        List<Lead> leadsToUpdate = new List<Lead>();    
        for (Lead l: newLeads) {
            if(l.Industry_Group__c == Null && l.Industry != Null){
                leadsToUpdate.add(l);
            }
        }
        if(leadsToUpdate.size() > 0) UpdateLeadsWithIndustryGroup(leadsToUpdate);
    }

    public void UpdateLeadsWithIndustryGroup(List<Lead> leadsToUpdate) {
        Map<String,String> ib_map = new Map<String,String>();
        for(IndustryBuckets__c ib: IndustryBuckets__c.getall().Values()){
            ib_map.put(ib.Industry__c, ib.Industry_Group__c);
        }
        for(Lead l: leadsToUpdate) {
            if(l.Industry_Group_Clearbit__c != null) {
                l.Industry_Group__c = l.Industry_Group_Clearbit__c;
            } else if(ib_map.keySet().Contains(l.Industry)){
                l.Industry_Group__c = ib_map.get(l.Industry);                
            }
        }
    }

    
}